# Generated by Django 2.1.4 on 2018-12-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditapp', '0003_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='friendly_name',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='test',
            name='geometry',
            field=models.IntegerField(default=1, verbose_name='Test Geometry'),
        ),
    ]
